### ISSUE TITLE
 Incorrect PDF linked in README.md

### ISSUE THREAD

**Issue by rsasaki0109** [cloudcjf/CCL#1]
Hello, I noticed that the PDF linked in the README.md of this repository is different from the actual paper it is supposed to link to. I would like to report this issue and request the correct PDF to be provided.

https://github.com/cloudcjf/CCL/blob/develop/README.md?plain=1#L5

**Comment by Chen-Xieyuanli** [comment]
Thanks for the checking and reminder. I've changed the correct link. You could also find the paper here: https://arxiv.org/pdf/2303.13952.pdf
